services:
  # users-api:
  #   build:
  #     context: .. # Assume que o Dockerfile está em docker/ e o contexto está na raiz do repositório
  #     dockerfile: docker/Dockerfile
  #   container_name: users-api
  #   ports:
  #     - "3333:3333"
  #   depends_on:
  #     - postgres
  #   environment:
  #     DATABASE_URL: postgres://postgres:password@postgres:5432/mydatabase
  #   networks:
  #     - app-network

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
